name       : akregator
version    : 19.12.1
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/akregator-19.12.1.tar.xz : e6f00777059e5b9fe2458a7e4248a59652f08d836518bf0395aaf2ed77ef4d52
homepage   : https://kde.org/applications/internet/org.kde.akregator
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.news
summary    : RSS Feed Reader
description: |
    Akregator is a news feed reader for the KDE desktop. It enables you to follow news sites, blogs and other RSS/Atom-enabled websites without the need to manually check for updates using a web browser. Akregator is designed to be both easy to use and to be powerful enough to read hundreds of news sources conveniently.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
    - syndication-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
