name       : akregator
version    : 18.08.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/akregator-18.08.2.tar.xz : bef2ff8ff8242eb5bbfb6461b1051c3d1899834c4f03894c158db99fc865843f
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : network.news
summary    : RSS Feed Reader
description: |
    Akregator is a news feed reader for the KDE desktop. It enables you to follow news sites, blogs and other RSS/Atom-enabled websites without the need to manually check for updates using a web browser. Akregator is designed to be both easy to use and to be powerful enough to read hundreds of news sources conveniently.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
    - syndication-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
