name       : akregator
version    : 20.12.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/akregator-20.12.2.tar.xz : f38d871496eb0a43ff1aa19cc71d0285233c77cc9fcb1516de7d6d2d5cadc287
homepage   : https://kde.org/applications/internet/org.kde.akregator
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.news
summary    : RSS Feed Reader
description: |
    Akregator is a news feed reader for the KDE desktop. It enables you to follow news sites, blogs and other RSS/Atom-enabled websites without the need to manually check for updates using a web browser. Akregator is designed to be both easy to use and to be powerful enough to read hundreds of news sources conveniently.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kimap-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syndication-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remvove doc
    rm -rf $installdir/usr/share/doc
